#287 Display hotkeys to detach from the container
jesseduffield/lazydocker pull request #411
Opened 2022-12-10 13:04 UTC by glendsoza

2022-12-13 08:05 UTC, jesseduffield commented on pkg/gui/containers_panel.go
> +	return gui.runSubprocessWithMessage(c, "By default, to detach from the container press ctrl-p then ctrl-q")
Can we internationalise this text?

2022-12-13 08:05 UTC, jesseduffield requested changes
Nice work :) One thing

2022-12-13 13:53 UTC, glendsoza commented
Thanks, @jesseduffield  for taking the time to review, i have internationalised the text as requested 

Please review

2023-07-21 07:43 UTC, jesseduffield commented
@glendsoza I've resolved conflicts but I can't push to your branch so I've recreated this in a separate PR: https://github.com/jesseduffield/lazydocker/pull/465

2023-07-21 07:43 UTC, closed without merging

2023-07-21 07:43 UTC, jesseduffield commented
PR is great btw! I'll add it in the next release