Fix mistakes in French translation
jesseduffield/lazydocker pull request #427
Opened 2023-01-25 17:13 UTC by paulus85

* This PR fixes several mistakes in the French translation on lazydocker.

2023-02-22 14:46 UTC, ghislaindurand commented on pkg/i18n/french.go
> +		CustomCommandTitle:        "Commande personalisée :",
CustomCommandTitle: "Commande personnalisée :",

2023-06-03 16:43 UTC, pablomalo requested changes
Thank you for these much-needed corrections. I hope your PR get approved soon. I took the liberty of making a few additional suggestions. Do not hesitate to discuss them with me if you disagree. 😄

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
> +		UnattachableContainerError: "Le conteneur ne peut pas être attaché. Vous devez exécuter le service avec le drapeau 'it' ou bien utiliser `stdin_open: true, tty: true` dans votre fichier docker-comp
```suggestion
		UnattachableContainerError: "Le conteneur ne peut pas être attaché. Vous devez exécuter le service avec le drapeau '-it' ou bien utiliser `stdin_open: true, tty: true` dans votre fichier docker-compose.yml",
```
Par souci d'homogénéité avec la version anglaise. 😄

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
> +		WaitingForContainerInfo:    "Le processus ne peut pas continuer avant que docker ne donne plus d'informations. Veuillez réessayer dans quelques instants.",
```suggestion
		WaitingForContainerInfo:    "Le processus ne peut pas continuer avant que docker ne fournisse plus d'informations. Veuillez réessayer dans quelques instants.",
```
Un peu plus soutenu ?

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
> +		CannotAccessDockerSocketError:     "Impossible d'accéder à la socket docker à: unix:///var/run/docker.sock\nLancez lazydocker en tant que root ou alors lisez https://docs.docker.com/install/linux/l
```suggestion
		CannotAccessDockerSocketError:     "Impossible d'accéder au socket docker à : unix:///var/run/docker.sock\nLancez lazydocker en tant que root ou lisez https://docs.docker.com/install/linux/linux-postinstall/",
```
Il me semble que parle généralement d'une soquette 🧦 mais d'_un_ socket. 😉

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
> +		CannotKillChildError:              "Trois secondes ont étés attendues pour l'arrêt des processus fils. Il y a possiblement un processus orphelin qui continue à tourner sur votre système.",
```suggestion
		CannotKillChildError:              "Trois secondes se sont écoulées depuis la demande d'arrêt des processus enfants. Il se peut qu'un processus orphelin continue à tourner sur votre système.",
```
"Processus enfants" : à la fois plus lisible et moins "genré" que "processus fils" ?

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
>  		StandaloneContainersTitle: "Conteneurs Autonomes",
```suggestion
		StandaloneContainersTitle: "Conteneurs autonomes",
```
Pour tous les titres, je serais partisan de ne mettre de majuscule qu'au premier mot, comme il est généralement d'usage en français.

![image](https://github.com/jesseduffield/lazydocker/assets/25877142/8f80c831-e558-4693-a134-0578876c5fba)

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
>  		CannotAttachStoppedContainerError: "Vous ne pouvez pas vous attacher à un conteneur en arrêt, vous devez le démarrer avant (ce que vous pouvez faire avec la touche 'r') (oui, je suis trop paresseux
```suggestion
		CannotAttachStoppedContainerError: "Vous ne pouvez pas vous attacher à un conteneur arrêté, vous devez auparavant le démarrer (ce que vous pouvez faire avec la touche 'r') (oui, je suis trop paresseux pour le faire automatiquement pour vous) (plutôt cool que je puisse communiquer en tête-à-tête avec vous au travers d'un message d'erreur, cependant)",
```

2023-06-03 16:43 UTC, pablomalo commented on pkg/i18n/french.go
>  		LogsTitle:                 "Enregistrements",
```suggestion
		LogsTitle:                 "Journaux",
```
On traduit généralement "system logs" par "journaux système", par exemple.

2023-07-19 07:56 UTC, paulus85 commented
@pablomalo Thanks for your feedbacks! I corrected my PR with your suggestions (and rebased the branch, as new translations have been added in the meantime).

Feel free to review again!

2023-09-12 20:03 UTC, pablomalo commented on pkg/i18n/french.go
> +		PressEnterToReturn:         "Appuyez sur Enter pour revenir à lazydocker (ce message peut être désactivé dans vos configurations en appliquant `gui.returnImmediately: true`)",
Appuyez sur Entrée ? 😄

2023-10-09 06:05 UTC, merged

2023-10-09 06:05 UTC, jesseduffield commented
Great work @paulus85 !